# Generated by Django 2.1.7 on 2019-04-26 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uer',
            name='visited',
            field=models.BooleanField(default=False),
        ),
    ]
