# Generated by Django 2.1.7 on 2019-04-23 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='pic',
            field=models.ImageField(null=True, upload_to='categories_photos'),
        ),
    ]
