# Generated by Django 2.1.5 on 2019-04-24 19:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('categories', '0003_auto_20190424_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='Members',
            field=models.ManyToManyField(related_name='members', to=settings.AUTH_USER_MODEL),
        ),
    ]
