# Generated by Django 2.1.5 on 2019-04-24 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_category_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='Members',
        ),
    ]
