# Generated by Django 2.1.5 on 2019-04-24 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20190423_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
