# Generated by Django 2.1.5 on 2019-04-26 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_blog_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='points',
        ),
    ]
