# Generated by Django 2.1.5 on 2019-04-26 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_remove_blog_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
