# Generated by Django 2.1.5 on 2019-04-28 15:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogs', '0005_blog_points'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='nay',
            unique_together={('nayer', 'nayed')},
        ),
        migrations.AlterUniqueTogether(
            name='yay',
            unique_together={('yayer', 'yayed')},
        ),
    ]
